# permissions for end users to view mydaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydaemonset-viewer-role
rules:
- apiGroups:
  - apps.opsblogs.cn
  resources:
  - mydaemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.opsblogs.cn
  resources:
  - mydaemonsets/status
  verbs:
  - get
