apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-demo 
subjects:
- kind: ServiceAccount
  name: demo-operator-controller-manager
  namespace: demo-operator-system
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io

